site_name: MAS Support

theme:
  name: carbon
  prefix: IBM

nav:
  - "Home": index.md
  - "use case":
    - "usecases": usecases.md
    - "Airgap install":
      - "Airgap installation": airgap/airgap.md

